// <auto-generated />
using System;
using Gestor_Salon_Belleza.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestor_Salon_Belleza.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260616232459_AddTurnoServiciosNav")]
    partial class AddTurnoServiciosNav
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Cliente", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Profesional", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Profesionales");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Profesional_Servicio", b =>
                {
                    b.Property<int>("Id_Profesional")
                        .HasColumnType("int");

                    b.Property<int>("Id_Servicio")
                        .HasColumnType("int");

                    b.HasKey("Id_Profesional", "Id_Servicio");

                    b.HasIndex("Id_Servicio");

                    b.ToTable("Profesional_Servicios");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Rol", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Rol"));

                    b.Property<string>("Rol_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Rol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Servicio", b =>
                {
                    b.Property<int>("Id_Servicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Servicio"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duracion_Minutos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id_Servicio");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Turno", b =>
                {
                    b.Property<int>("Id_Turno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Turno"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Cliente")
                        .HasColumnType("int");

                    b.Property<int>("Id_Profesional")
                        .HasColumnType("int");

                    b.Property<int?>("ServicioId_Servicio")
                        .HasColumnType("int");

                    b.HasKey("Id_Turno");

                    b.HasIndex("Id_Cliente");

                    b.HasIndex("Id_Profesional");

                    b.HasIndex("ServicioId_Servicio");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Turno_Servicio", b =>
                {
                    b.Property<int>("Id_Turno")
                        .HasColumnType("int");

                    b.Property<int>("Id_Servicio")
                        .HasColumnType("int");

                    b.HasKey("Id_Turno", "Id_Servicio");

                    b.HasIndex("Id_Servicio");

                    b.ToTable("Turno_Servicios");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("Id_Rol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.UsuarioLoginExterno", b =>
                {
                    b.Property<int>("Id_LoginExterno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_LoginExterno"));

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id_LoginExterno");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Usuario_LoginsExternos");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Cliente", b =>
                {
                    b.HasOne("Gestor_Salon_Belleza.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Profesional", b =>
                {
                    b.HasOne("Gestor_Salon_Belleza.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Profesional_Servicio", b =>
                {
                    b.HasOne("Gestor_Salon_Belleza.Models.Profesional", "Profesional")
                        .WithMany("Profesional_Servicios")
                        .HasForeignKey("Id_Profesional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestor_Salon_Belleza.Models.Servicio", "Servicio")
                        .WithMany("Profesional_Servicios")
                        .HasForeignKey("Id_Servicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesional");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Turno", b =>
                {
                    b.HasOne("Gestor_Salon_Belleza.Models.Cliente", "Cliente")
                        .WithMany("Turnos")
                        .HasForeignKey("Id_Cliente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Gestor_Salon_Belleza.Models.Profesional", "Profesional")
                        .WithMany("Turnos")
                        .HasForeignKey("Id_Profesional")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Gestor_Salon_Belleza.Models.Servicio", null)
                        .WithMany("Turnos")
                        .HasForeignKey("ServicioId_Servicio");

                    b.Navigation("Cliente");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Turno_Servicio", b =>
                {
                    b.HasOne("Gestor_Salon_Belleza.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("Id_Servicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestor_Salon_Belleza.Models.Turno", "Turno")
                        .WithMany("TurnoServicios")
                        .HasForeignKey("Id_Turno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Usuario", b =>
                {
                    b.HasOne("Gestor_Salon_Belleza.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.UsuarioLoginExterno", b =>
                {
                    b.HasOne("Gestor_Salon_Belleza.Models.Usuario", "Usuario")
                        .WithMany("LoginsExternos")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Cliente", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Profesional", b =>
                {
                    b.Navigation("Profesional_Servicios");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Servicio", b =>
                {
                    b.Navigation("Profesional_Servicios");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Turno", b =>
                {
                    b.Navigation("TurnoServicios");
                });

            modelBuilder.Entity("Gestor_Salon_Belleza.Models.Usuario", b =>
                {
                    b.Navigation("LoginsExternos");
                });
#pragma warning restore 612, 618
        }
    }
}
